[package]
name = "easyjs"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
wasm-bindgen = "0.2.95"
getrandom = { version = "0.2.15", features = ["js"]}
boa_engine = "0.19.0"