[package]
name = "easyjsc"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.95"
wasm-encoder = "0.224.0"
easy_utils = { path = "../easy_utils" }
regex = "1.11.1"

[lints.rust]
unused = "allow"
